---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ctlplane
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ipAddressPools:
  - ctlplane
  interfaces:
  - enp1s0
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internalapi
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ipAddressPools:
  - internalapi
  interfaces:
  - enp1s0.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: storage
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ipAddressPools:
  - storage
  interfaces:
  - enp1s0.21
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tenant
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ipAddressPools:
  - tenant
  interfaces:
  - enp1s0.22