apiVersion: v1
data:
  nfs-cinder-conf: W25mc10KbmFzX2hvc3Q9MTkyLjE2OC4xMjMuMTAwCm5hc19zaGFyZV9wYXRoPS9uZnMvY2luZGVy
kind: Secret
metadata:
  name: cinder-nfs-config
  namespace: openstack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque